trainer: global

dataset:
  - src: datasets/FG-GMAE/data.lmdb
    normalize_labels: True

# logger: wandb

task:
  dataset: single_point_lmdb
  type: regression
  metric: mae
  labels:
    - relaxed energy

model:
  name: adsmt_arch
  pretrain: True
  ckpt_path: model_ckpts/pretrain/FG-GMAE/gemnet-oc.pt
  freeze_nblock: 0
  use_pbc: True
  otf_graph: True
  regress_forces: False
  desc_layers: 2
  desc_hidden_dim: 128
  graph_encoder: gemnet_oc
  graph_encoder_args:
    num_spherical: 7
    num_radial: 128
    num_blocks: 3
    emb_size_atom: 128
    emb_size_edge: 256
    emb_size_trip_in: 64
    emb_size_trip_out: 64
    emb_size_quad_in: 32
    emb_size_quad_out: 32
    emb_size_aint_in: 64
    emb_size_aint_out: 64
    emb_size_rbf: 16
    emb_size_cbf: 16
    emb_size_sbf: 32
    num_before_skip: 2
    num_after_skip: 2
    num_concat: 1
    num_atom: 3
    num_output_afteratom: 3
    cutoff: 12.0
    cutoff_qint: 12.0
    cutoff_aeaint: 12.0
    cutoff_aint: 12.0
    max_neighbors: 30
    max_neighbors_qint: 8
    max_neighbors_aeaint: 20
    max_neighbors_aint: 1000
    rbf:
      name: gaussian
    envelope:
      name: polynomial
      exponent: 5
    cbf:
      name: spherical_harmonics
    sbf:
      name: legendre_outer
    extensive: True
    output_init: HeOrthogonal
    activation: silu
    scale_file: configs/gemnet-oc.pt

    quad_interaction: True
    atom_edge_interaction: True
    edge_atom_interaction: True
    atom_interaction: True

    num_atom_emb_layers: 2
    num_global_out_layers: 2
    qint_tags: [1, 2]
  cross_modal_args:
    vec_emb_dim: 128
    node_emb_dim: 128
    hidden_dim: 128
    out_channels: 1
    num_gaussians: 100
    num_heads: 4
    attn_layers: 1
    mlp_layers: 3
    dropout: 0.0
    act: silu

optim:
  batch_size: 16
  eval_batch_size: 16
  load_balancing: atoms
  num_workers: 8
  lr_initial: 5.e-4
  optimizer: AdamW
  optimizer_params: {"amsgrad": True}
  scheduler: ReduceLROnPlateau
  mode: min
  factor: 0.6
  patience: 3
  max_epochs: 60
  ema_decay: 0.999
  clip_grad_norm: 10
  weight_decay: 0